/*
this file is be generated by hand, edit here
*/

#include "custom_resources.h"

dma_info_t ad_ENUM_0 = {
	.addr = 1024*1024*15,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};
dma_info_t ad_ENUM_1 = {
	.addr = 1024*1024*14,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};
dma_info_t ad_ENUM_2 = {
	.addr = 1024*1024*13,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};
dma_info_t ad_ENUM_3 = {
	.addr = 1024*1024*12,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};
dma_info_t ad_ENUM_4 = {
	.addr = 1024*1024*11,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};
dma_info_t ad_ENUM_5 = {
	.addr = 1024*1024*10,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};

dma_info_t ad_ENUM_6 = {
	.addr = 1024*1024*9,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};

dma_info_t ad_ENUM_7 = {
	.addr = 1024*1024*8,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};

dma_info_t ad_ENUM_8 = {
	.addr = 1024*1024*7,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};

dma_info_t ad_ENUM_9 = {
	.addr = 1024*1024*6,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};


dma_info_t ad_BTjump_click = {
	.addr = 0,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};
dma_info_t ad_BTjump_normal = {
	.addr = 0,
	.src_w = 720,
	.x = 0,
	.y = 0,
	.w = 720,
	.h = 720,
};