
/*
this file is be generated by hand, edit here
*/

#ifndef CUSTOM_RESOURCES_H
#define CUSTOM_RESOURCES_H
#include "lt768ui_interface.h"

extern dma_info_t ad_ENUM_0;
extern dma_info_t ad_ENUM_1;
extern dma_info_t ad_ENUM_2;
extern dma_info_t ad_ENUM_3;
extern dma_info_t ad_ENUM_4;
extern dma_info_t ad_ENUM_5;
extern dma_info_t ad_ENUM_6;
extern dma_info_t ad_ENUM_7;
extern dma_info_t ad_ENUM_8;
extern dma_info_t ad_ENUM_9;
extern dma_info_t ad_BTjump_normal;
extern dma_info_t ad_BTjump_click;

#endif